### ISSUE TITLE
nx issues

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack-ecosystem-ci#11]
Error: Command failed with ENOENT: e2e rspack-e2e
* https://github.com/web-infra-dev/rspack-ecosystem-ci/actions/runs/5238403107/jobs/9459886174

error Couldn't find any versions for "@rspack/binding-darwin-arm64" that matches "workspace:*"
* https://github.com/web-infra-dev/rspack-ecosystem-ci/actions/runs/5250632750/jobs/9484771948

**Comment by ahabhgk** [comment]
fixed in https://github.com/web-infra-dev/rspack-ecosystem-ci/commit/e11d88747beec945f9505f04a17ada30087de1eb
